# Preview configuration for PR deployments
baseURL = 'https://gh.ryanwallace.cloud'
languageCode = 'en-us'
title = 'ryanwallace.cloud (Preview)'
theme = "poison"
pygmentsCodefences = true
pygmentsUseClasses = true
copyright = "Ryan Wallace"
pluralizelisttitles = false

# Preview environment settings
[params]
environment = "preview"
enableAnalytics = false
enableComments = false

[params.author]
about = "Greater Boston SRE"

footerCopyright = "Ryan Wallace (Preview)"
brand_image = "/images/brand-image.jpeg"

brand = "Ryan Wallace (Preview)"
github_url = "https://github.com/cubismod"
linkedin_url = "https://www.linkedin.com/in/ryanswallace/"

link_color_dark = "#00c0a3"
link_color = "#00896f"
sidebar_bg_color = "#2f0d38"
content_bg_color_dark = "#1e0624"

menu = [
    { Name = "About", URL = "/about/" },
    { Name = "Posts", URL = "/posts/", Pre = "Recent", HasChildren = true, Limit = 5 },
]

[privacy]
[privacy.disqus]
disable = true
[privacy.googleAnalytics]
disable = true
[privacy.instagram]
simple = true

[markup]
[markup.tableOfContents]
startLevel = 2
endLevel = 5
ordered = false
