version: '3'

dotenv:
- ryanwallace.cloud/map/.env

tasks:
  dev:
    dir: ryanwallace.cloud
    cmds:
    - hugo server -D
  map_build:
    dir: ryanwallace.cloud/map
    cmds:
    - yarn build
    - yarn clean
    - yarn move
  format:
    dir: ryanwallace.cloud/map
    cmds:
    - yarn prettier --write .
  typecheck:
    dir: ryanwallace.cloud/map
    cmds:
    - yarn tsc --noEmit
