version: "3"

dotenv:
  - ryanwallace.cloud/map/.env

tasks:
  nofastrender:
    dir: ryanwallace.cloud
    cmds:
      - hugo server -D --disableFastRender
  dev:
    dir: ryanwallace.cloud
    cmds:
      - hugo server -D
  build:
    dir: ryanwallace.cloud/map
    cmds:
      - yarn build
      - yarn clean
      - yarn move
  clean:
    dir: ryanwallace.cloud/map
    cmds:
      - yarn clean
  formattheme:
    dir: ryanwallace.cloud/themes/poison
    cmds:
      - npx prettier --write .
  format:
    cmds:
      - npx prettier --write .
  typecheck:
    dir: ryanwallace.cloud/map
    cmds:
      - yarn tsc --noEmit
  cleanpublic:
    dir: ryanwallace.cloud
    cmds:
      - rm -rf public/
