version: "3"

dotenv:
  - ryanwallace.cloud/map/.env

tasks:
  dev:
    dir: ryanwallace.cloud
    cmds:
      - hugo server -D
  build:
    dir: ryanwallace.cloud/map
    cmds:
      - yarn build
      - yarn clean
      - yarn move
  clean:
    dir: ryanwallace.cloud/map
    cmds:
      - yarn clean
  format:
    cmds:
      - npx prettier --write .
  typecheck:
    dir: ryanwallace.cloud/map
    cmds:
      - yarn tsc --noEmit
  nocache:
    dir: ryanwallace.cloud/map
    cmds:
      - yarn build:nocache
      - yarn clean
      - yarn move
