version: "3"

tasks:
  nofastrender:
    dir: ryanwallace.cloud
    cmds:
      - hugo server -D --disableFastRender
  dev:
    dir: ryanwallace.cloud
    cmds:
      - hugo server -D
  formattheme:
    dir: ryanwallace.cloud/themes/poison
    cmds:
      - pnpm dlx prettier --write .
  format:
    cmds:
      - pnpm dlx prettier --write .
  cleanpublic:
    dir: ryanwallace.cloud
    cmds:
      - rm -rf public/
