version: "3"

dotenv:
  - ryanwallace.cloud/map/.env

tasks:
  nofastrender:
    dir: ryanwallace.cloud
    cmds:
      - hugo server -D --disableFastRender
  dev:
    dir: ryanwallace.cloud
    cmds:
      - hugo server -D
  build:
    dir: ryanwallace.cloud/map
    cmds:
      - pnpm build
      - pnpm clean
      - pnpm move
      - pnpm title
      - pnpm title:alerts
      - pnpm title:track
  builddev:
    dir: ryanwallace.cloud/map
    cmds:
      - pnpm build:dev
      - pnpm clean
      - pnpm move
      - pnpm title
      - pnpm title:alerts
      - pnpm title:track
  watch:
    dir: ryanwallace.cloud/map
    cmds:
      - pnpm watch
  clean:
    dir: ryanwallace.cloud/map
    cmds:
      - pnpm clean
  formattheme:
    dir: ryanwallace.cloud/themes/poison
    cmds:
      - pnpm dlx prettier --write .
  format:
    cmds:
      - pnpm dlx prettier --write .
  check:
    dir: ryanwallace.cloud/map
    cmds:
      - pnpm typecheck
  cleanpublic:
    dir: ryanwallace.cloud
    cmds:
      - rm -rf public/
  nocache:
    dir: ryanwallace.cloud/map
    cmds:
      - pnpm build:nocache
      - pnpm clean
      - pnpm move
      - pnpm title
      - pnpm title:alerts
      - pnpm title:track
  pnpm_setup:
    dir: ryanwallace.cloud/map
    cmds:
      - npm install --global corepack@latest
      - corepack enable pnpm
