name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

on:
  push:
    branches: ["main"]
  pull_request:
  merge_group:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@61b9e3751b92087fd0b06925ba6dd6314e06f089 # master
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4
      - name: build
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7
        with:
          context: .
          push: false
          build-args: |
            MT_KEY=${{ secrets.MT_KEY }}
            VEHICLES_URL=https://imt.ryanwallace.cloud
            MBTA_API_BASE=
            TRACK_PREDICTION_API=https://imt.ryanwallace.cloud
            BOS_URL=https://bos.ryanwallace.cloud
