name: Cleanup Preview

on:
  pull_request:
    branches: [ main ]
    types: [ closed ]

jobs:
  cleanup:
    # Skip this job if the PR is from renovate bot
    if: github.actor != 'cubis-renovate[bot]'
    
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pages: write
      id-token: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Cleanup preview deployment
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.event.number;
            
            // Comment on the PR that the preview has been cleaned up
            const comment = `## 🧹 Preview Cleaned Up
            
            The preview deployment for this PR has been removed.
            
            ---
            *This cleanup was performed automatically by GitHub Actions*`;
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: comment
            });
            
            console.log(`Preview cleanup completed for PR #${prNumber}`);
