name: Cleanup Preview

on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  cleanup:
    # Skip this job if the PR is from renovate bot
    if: github.actor != 'cubis-renovate[bot]'

    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Restore cache
        uses: actions/cache/restore@v4
        with:
          path: ryanwallace.cloud/
          key: preview

      - name: Remove old artifacts
        working-directory: ryanwallace.cloud/map
        run: |
          PREVIEW_FOLDER=preview/$PR_NUMBER
          rm -rf $PREVIEW_FOLDER/*
        env:
          HUGO_ENVIRONMENT: preview
          HUGO_ENV: preview
          PR_NUMBER: ${{ github.event.number }}

      - name: Save cache
        uses: actions/cache/save@v4
        with:
          path: ryanwallace.cloud/
          key: preview

      - name: Setup Pages
        uses: actions/configure-pages@v4
